CREATE TABLE [dbo].[School]
(
	[Id]			INT		 NOT NULL PRIMARY KEY CLUSTERED IDENTITY(1, 1),
	[Name]			NVARCHAR NOT NULL,
	[AddressLine1]	NVARCHAR NOT NULL,
	[AddressLine2]	NVARCHAR NULL,
	[City]			NVARCHAR NOT NULL,
	[PostalCode]	NVARCHAR NOT NULL,
	[StateId]		NVARCHAR NOT NULL,
)
